services:
  - type: worker
    name: louisville-scraper
    env: python
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /app/credentials
      cp credentials/gcreds.json /app/credentials/gcreds.json
    startCommand: python scraper.py
    disk:
      name: credentials-disk
      mountPath: /app/credentials
