services:
  - type: worker
    name: louisville-scraper
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    disk:
      name: credentials-disk
      mountPath: /app/credentials